//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser_BIC.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.cbr.ru/", ConfigurationName="ServiceReference1.CreditOrgInfoSoap")]
    public interface CreditOrgInfoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumBIC_XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode EnumBIC_XML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumBIC_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> EnumBIC_XMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetFormsMaxDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetFormsMaxDate(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetFormsMaxDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetFormsMaxDateAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/LastUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime LastUpdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/LastUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> LastUpdateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumBIC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EnumBIC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/EnumBIC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EnumBICAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data101FormExXML(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormExXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FormExXMLAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data101FormEx(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormEx", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data101FormExAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data101FormXML(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FormXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FormXMLAsync(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101Form", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data101Form(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101Form", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data101FormAsync(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data101FullXML(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullXMLAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data101FullExXML(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExXMLAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data101FullEx(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullEx", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data101FullExAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExV2XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data101FullExV2XML(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExV2XML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExV2XMLAsync(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data101FullExV2(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullExV2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data101FullExV2Async(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101Full", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data101Full(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101Full", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data101FullAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullV2XML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data101FullV2XML(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullV2XML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullV2XMLAsync(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data101FullV2(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data101FullV2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data101FullV2Async(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data102FormExXML(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormExXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormExXMLAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data102FormEx(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormEx", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data102FormExAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data102FormXML(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102FormXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormXMLAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102Form", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data102Form(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data102Form", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data102FormAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form102IndicatorsEnumXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Form102IndicatorsEnumXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form102IndicatorsEnumXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Form102IndicatorsEnumXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form102IndicatorsEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Form102IndicatorsEnum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form102IndicatorsEnum", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Form102IndicatorsEnumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form101IndicatorsEnumXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Form101IndicatorsEnumXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form101IndicatorsEnumXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Form101IndicatorsEnumXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form101IndicatorsEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Form101IndicatorsEnum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Form101IndicatorsEnum", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Form101IndicatorsEnumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegNumToIntCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        double RegNumToIntCode(double RegNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegNumToIntCode", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RegNumToIntCodeAsync(double RegNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IntCodeToRegNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        double IntCodeToRegNum(double IntNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/IntCodeToRegNum", ReplyAction="*")]
        System.Threading.Tasks.Task<double> IntCodeToRegNumAsync(double IntNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BicToIntCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        double BicToIntCode(string BicCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BicToIntCode", ReplyAction="*")]
        System.Threading.Tasks.Task<double> BicToIntCodeAsync(string BicCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BicToRegNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int BicToRegNumber(string BicCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/BicToRegNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BicToRegNumberAsync(string BicCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegionsEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet RegionsEnum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegionsEnum", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> RegionsEnumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegionsEnumXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode RegionsEnumXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/RegionsEnumXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RegionsEnumXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByRegionCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet SearchByRegionCode(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByRegionCode", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchByRegionCodeAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByRegionCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode SearchByRegionCodeXML(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByRegionCodeXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByRegionCodeXMLAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByNameXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode SearchByNameXML(string NamePart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByNameXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByNameXMLAsync(string NamePart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet SearchByName(string NamePart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchByNameAsync(string NamePart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode CreditInfoByIntCodeXML(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeXMLAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeExXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode CreditInfoByIntCodeExXML(double[] InternalCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeExXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeExXMLAsync(double[] InternalCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet CreditInfoByIntCodeEx(double[] InternalCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCodeEx", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CreditInfoByIntCodeExAsync(double[] InternalCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet CreditInfoByIntCode(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/CreditInfoByIntCode", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CreditInfoByIntCodeAsync(double InternalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOffices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet GetOffices(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOffices", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOfficesAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesByRegion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet GetOfficesByRegion(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOfficesByRegionAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetOfficesXML(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesXMLAsync(double IntCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesByRegionXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode GetOfficesByRegionXML(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetOfficesByRegionXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesByRegionXMLAsync(int RegCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134FormFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data134FormFullXML(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134FormFullXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data134FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Olap134Form", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Olap134Form(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Olap134Form", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Olap134FormAsync(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135FormFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data135FormFull(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135FormFull", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data135FormFullAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135FormFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data135FormFullXML(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data135FormFullXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data135FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123FormFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data123FormFull(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123FormFull", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data123FormFullAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123FormFullXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode Data123FormFullXML(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data123FormFullXML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> Data123FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF123", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.DateTime[] GetDatesForF123(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF123", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF123Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF101", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.DateTime[] GetDatesForF101(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF101", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF101Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF102", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.DateTime[] GetDatesForF102(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF102", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF102Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF134", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.DateTime[] GetDatesForF134(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF134", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF134Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF135", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.DateTime[] GetDatesForF135(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/GetDatesForF135", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF135Async(int CredprgNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134FormFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataSet Data134FormFull(int CredorgNumber, System.DateTime OnDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web.cbr.ru/Data134FormFull", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Data134FormFullAsync(int CredorgNumber, System.DateTime OnDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreditOrgInfoSoapChannel : Parser_BIC.ServiceReference1.CreditOrgInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditOrgInfoSoapClient : System.ServiceModel.ClientBase<Parser_BIC.ServiceReference1.CreditOrgInfoSoap>, Parser_BIC.ServiceReference1.CreditOrgInfoSoap {
        
        public CreditOrgInfoSoapClient() {
        }
        
        public CreditOrgInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditOrgInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditOrgInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditOrgInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode EnumBIC_XML() {
            return base.Channel.EnumBIC_XML();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> EnumBIC_XMLAsync() {
            return base.Channel.EnumBIC_XMLAsync();
        }
        
        public System.DateTime GetFormsMaxDate(int code) {
            return base.Channel.GetFormsMaxDate(code);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetFormsMaxDateAsync(int code) {
            return base.Channel.GetFormsMaxDateAsync(code);
        }
        
        public System.DateTime LastUpdate() {
            return base.Channel.LastUpdate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> LastUpdateAsync() {
            return base.Channel.LastUpdateAsync();
        }
        
        public System.Data.DataSet EnumBIC() {
            return base.Channel.EnumBIC();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EnumBICAsync() {
            return base.Channel.EnumBICAsync();
        }
        
        public System.Xml.XmlNode Data101FormExXML(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FormExXML(CredorgNumbers, IndID, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FormExXMLAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FormExXMLAsync(CredorgNumbers, IndID, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data101FormEx(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FormEx(CredorgNumbers, IndID, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data101FormExAsync(object[] CredorgNumbers, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FormExAsync(CredorgNumbers, IndID, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Data101FormXML(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FormXML(CredorgNumber, IndID, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FormXMLAsync(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FormXMLAsync(CredorgNumber, IndID, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data101Form(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101Form(CredorgNumber, IndID, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data101FormAsync(int CredorgNumber, int IndID, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FormAsync(CredorgNumber, IndID, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Data101FullXML(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullXML(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullXMLAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullXMLAsync(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Data101FullExXML(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullExXML(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExXMLAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullExXMLAsync(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data101FullEx(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullEx(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data101FullExAsync(object[] CredorgNumbers, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullExAsync(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Data101FullExV2XML(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullExV2XML(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullExV2XMLAsync(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullExV2XMLAsync(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data101FullExV2(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullExV2(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data101FullExV2Async(object[] CredorgNumbers, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullExV2Async(CredorgNumbers, IndCode, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data101Full(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101Full(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data101FullAsync(int CredorgNumber, int IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullAsync(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Data101FullV2XML(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullV2XML(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data101FullV2XMLAsync(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullV2XMLAsync(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data101FullV2(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullV2(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data101FullV2Async(int CredorgNumber, string IndCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data101FullV2Async(CredorgNumber, IndCode, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Data102FormExXML(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102FormExXML(CredorgNumbers, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormExXMLAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102FormExXMLAsync(CredorgNumbers, SymbCode, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data102FormEx(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102FormEx(CredorgNumbers, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data102FormExAsync(object[] CredorgNumbers, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102FormExAsync(CredorgNumbers, SymbCode, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Data102FormXML(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102FormXML(CredorgNumber, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data102FormXMLAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102FormXMLAsync(CredorgNumber, SymbCode, DateFrom, DateTo);
        }
        
        public System.Data.DataSet Data102Form(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102Form(CredorgNumber, SymbCode, DateFrom, DateTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data102FormAsync(int CredorgNumber, int SymbCode, System.DateTime DateFrom, System.DateTime DateTo) {
            return base.Channel.Data102FormAsync(CredorgNumber, SymbCode, DateFrom, DateTo);
        }
        
        public System.Xml.XmlNode Form102IndicatorsEnumXML() {
            return base.Channel.Form102IndicatorsEnumXML();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Form102IndicatorsEnumXMLAsync() {
            return base.Channel.Form102IndicatorsEnumXMLAsync();
        }
        
        public System.Data.DataSet Form102IndicatorsEnum() {
            return base.Channel.Form102IndicatorsEnum();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Form102IndicatorsEnumAsync() {
            return base.Channel.Form102IndicatorsEnumAsync();
        }
        
        public System.Xml.XmlNode Form101IndicatorsEnumXML() {
            return base.Channel.Form101IndicatorsEnumXML();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Form101IndicatorsEnumXMLAsync() {
            return base.Channel.Form101IndicatorsEnumXMLAsync();
        }
        
        public System.Data.DataSet Form101IndicatorsEnum() {
            return base.Channel.Form101IndicatorsEnum();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Form101IndicatorsEnumAsync() {
            return base.Channel.Form101IndicatorsEnumAsync();
        }
        
        public double RegNumToIntCode(double RegNumber) {
            return base.Channel.RegNumToIntCode(RegNumber);
        }
        
        public System.Threading.Tasks.Task<double> RegNumToIntCodeAsync(double RegNumber) {
            return base.Channel.RegNumToIntCodeAsync(RegNumber);
        }
        
        public double IntCodeToRegNum(double IntNumber) {
            return base.Channel.IntCodeToRegNum(IntNumber);
        }
        
        public System.Threading.Tasks.Task<double> IntCodeToRegNumAsync(double IntNumber) {
            return base.Channel.IntCodeToRegNumAsync(IntNumber);
        }
        
        public double BicToIntCode(string BicCode) {
            return base.Channel.BicToIntCode(BicCode);
        }
        
        public System.Threading.Tasks.Task<double> BicToIntCodeAsync(string BicCode) {
            return base.Channel.BicToIntCodeAsync(BicCode);
        }
        
        public int BicToRegNumber(string BicCode) {
            return base.Channel.BicToRegNumber(BicCode);
        }
        
        public System.Threading.Tasks.Task<int> BicToRegNumberAsync(string BicCode) {
            return base.Channel.BicToRegNumberAsync(BicCode);
        }
        
        public System.Data.DataSet RegionsEnum() {
            return base.Channel.RegionsEnum();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> RegionsEnumAsync() {
            return base.Channel.RegionsEnumAsync();
        }
        
        public System.Xml.XmlNode RegionsEnumXML() {
            return base.Channel.RegionsEnumXML();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RegionsEnumXMLAsync() {
            return base.Channel.RegionsEnumXMLAsync();
        }
        
        public System.Data.DataSet SearchByRegionCode(int RegCode) {
            return base.Channel.SearchByRegionCode(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchByRegionCodeAsync(int RegCode) {
            return base.Channel.SearchByRegionCodeAsync(RegCode);
        }
        
        public System.Xml.XmlNode SearchByRegionCodeXML(int RegCode) {
            return base.Channel.SearchByRegionCodeXML(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByRegionCodeXMLAsync(int RegCode) {
            return base.Channel.SearchByRegionCodeXMLAsync(RegCode);
        }
        
        public System.Xml.XmlNode SearchByNameXML(string NamePart) {
            return base.Channel.SearchByNameXML(NamePart);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SearchByNameXMLAsync(string NamePart) {
            return base.Channel.SearchByNameXMLAsync(NamePart);
        }
        
        public System.Data.DataSet SearchByName(string NamePart) {
            return base.Channel.SearchByName(NamePart);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchByNameAsync(string NamePart) {
            return base.Channel.SearchByNameAsync(NamePart);
        }
        
        public System.Xml.XmlNode CreditInfoByIntCodeXML(double InternalCode) {
            return base.Channel.CreditInfoByIntCodeXML(InternalCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeXMLAsync(double InternalCode) {
            return base.Channel.CreditInfoByIntCodeXMLAsync(InternalCode);
        }
        
        public System.Xml.XmlNode CreditInfoByIntCodeExXML(double[] InternalCodes) {
            return base.Channel.CreditInfoByIntCodeExXML(InternalCodes);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CreditInfoByIntCodeExXMLAsync(double[] InternalCodes) {
            return base.Channel.CreditInfoByIntCodeExXMLAsync(InternalCodes);
        }
        
        public System.Data.DataSet CreditInfoByIntCodeEx(double[] InternalCodes) {
            return base.Channel.CreditInfoByIntCodeEx(InternalCodes);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CreditInfoByIntCodeExAsync(double[] InternalCodes) {
            return base.Channel.CreditInfoByIntCodeExAsync(InternalCodes);
        }
        
        public System.Data.DataSet CreditInfoByIntCode(double InternalCode) {
            return base.Channel.CreditInfoByIntCode(InternalCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CreditInfoByIntCodeAsync(double InternalCode) {
            return base.Channel.CreditInfoByIntCodeAsync(InternalCode);
        }
        
        public System.Data.DataSet GetOffices(double IntCode) {
            return base.Channel.GetOffices(IntCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOfficesAsync(double IntCode) {
            return base.Channel.GetOfficesAsync(IntCode);
        }
        
        public System.Data.DataSet GetOfficesByRegion(int RegCode) {
            return base.Channel.GetOfficesByRegion(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOfficesByRegionAsync(int RegCode) {
            return base.Channel.GetOfficesByRegionAsync(RegCode);
        }
        
        public System.Xml.XmlNode GetOfficesXML(double IntCode) {
            return base.Channel.GetOfficesXML(IntCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesXMLAsync(double IntCode) {
            return base.Channel.GetOfficesXMLAsync(IntCode);
        }
        
        public System.Xml.XmlNode GetOfficesByRegionXML(int RegCode) {
            return base.Channel.GetOfficesByRegionXML(RegCode);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetOfficesByRegionXMLAsync(int RegCode) {
            return base.Channel.GetOfficesByRegionXMLAsync(RegCode);
        }
        
        public System.Xml.XmlNode Data134FormFullXML(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data134FormFullXML(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data134FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data134FormFullXMLAsync(CredorgNumber, OnDate);
        }
        
        public System.Data.DataSet Olap134Form(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate) {
            return base.Channel.Olap134Form(Code, CredorgNumber, FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Olap134FormAsync(string Code, int CredorgNumber, System.DateTime FromDate, System.DateTime ToDate) {
            return base.Channel.Olap134FormAsync(Code, CredorgNumber, FromDate, ToDate);
        }
        
        public System.Data.DataSet Data135FormFull(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data135FormFull(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data135FormFullAsync(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data135FormFullAsync(CredorgNumber, OnDate);
        }
        
        public System.Xml.XmlNode Data135FormFullXML(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data135FormFullXML(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data135FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data135FormFullXMLAsync(CredorgNumber, OnDate);
        }
        
        public System.Data.DataSet Data123FormFull(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data123FormFull(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data123FormFullAsync(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data123FormFullAsync(CredorgNumber, OnDate);
        }
        
        public System.Xml.XmlNode Data123FormFullXML(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data123FormFullXML(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> Data123FormFullXMLAsync(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data123FormFullXMLAsync(CredorgNumber, OnDate);
        }
        
        public System.DateTime[] GetDatesForF123(int CredprgNumber) {
            return base.Channel.GetDatesForF123(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF123Async(int CredprgNumber) {
            return base.Channel.GetDatesForF123Async(CredprgNumber);
        }
        
        public System.DateTime[] GetDatesForF101(int CredprgNumber) {
            return base.Channel.GetDatesForF101(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF101Async(int CredprgNumber) {
            return base.Channel.GetDatesForF101Async(CredprgNumber);
        }
        
        public System.DateTime[] GetDatesForF102(int CredprgNumber) {
            return base.Channel.GetDatesForF102(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF102Async(int CredprgNumber) {
            return base.Channel.GetDatesForF102Async(CredprgNumber);
        }
        
        public System.DateTime[] GetDatesForF134(int CredprgNumber) {
            return base.Channel.GetDatesForF134(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF134Async(int CredprgNumber) {
            return base.Channel.GetDatesForF134Async(CredprgNumber);
        }
        
        public System.DateTime[] GetDatesForF135(int CredprgNumber) {
            return base.Channel.GetDatesForF135(CredprgNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetDatesForF135Async(int CredprgNumber) {
            return base.Channel.GetDatesForF135Async(CredprgNumber);
        }
        
        public System.Data.DataSet Data134FormFull(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data134FormFull(CredorgNumber, OnDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Data134FormFullAsync(int CredorgNumber, System.DateTime OnDate) {
            return base.Channel.Data134FormFullAsync(CredorgNumber, OnDate);
        }
    }
}
